version: "3.9"

volumes:
    PersonDB:

services:
    db:
        image: "mcr.microsoft.com/mssql/server"
        container_name: mssql
        environment:
            SA_PASSWORD: "Master@123"
            ACCEPT_EULA: "Y"
        ports:
          - "1433:1433"
        volumes:
            - PersonDB:/var/lib/mssql
    api:
        build: 
          context: .
          dockerfile: teste-api/src/TesteApi.Api/Dockerfile
        ports:
            - "5000:80"
        depends_on:
            - db
    app:
        build: 
            context: .
            dockerfile: teste-app/Dockerfile
        ports:
            - "4200:80"
