version: "3.9"
services:
    api:
        build: 
          context: .
          dockerfile: teste-api/src/TesteApi.Api/Dockerfile
        ports:
            - "5000:80"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Master@123"
            ACCEPT_EULA: "Y"
        ports:
          - "1433:1433"
    app:
        build: 
            context: .
            dockerfile: teste-app/Dockerfile
        ports:
            - "4200:80"
